name: TVerRec

on:
  workflow_dispatch:
  schedule:
    - cron: '30 8 * * 6'

jobs:
  download-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Clone this repository
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Clone TVerRec repository
        uses: actions/checkout@v4
        with: 
          repository: dongaba/TVerRec
          ref: master
          path: TVerRec

      - name: Create required directories
        run: mkdir -p TVerRec/downloads TVerRec/temp TVerRec/save

      - name: Copy configurations
        run: |
          pwd
          ls
          cp keyword.conf user_settings.ps1 TVerRec/conf/

      - name: Install PowerShell
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get update
          sudo apt-get install -y wget apt-transport-https software-properties-common
          wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
          sudo dpkg -i --force-confnew packages-microsoft-prod.deb
          rm packages-microsoft-prod.deb
          sudo apt-get update
          sudo apt-get install -y powershell
          
      - name: Install WireGuard
        run: sudo apt-get update && sudo apt-get install -y wireguard

      - name: Write private key
        run: |
          echo "${{ secrets.WG_PRIVATE_KEY }}" > privatekey
          chmod 600 privatekey

      - name: Setup wg0 interface
        run: |
          sudo ip link add dev wg0 type wireguard
          sudo ip address add dev wg0 10.2.0.2 peer 10.2.0.1

      - name: Configure WireGuard peer
        run: |
          sudo wg set wg0 \
            listen-port 51820 \
            private-key privatekey \
            peer ${{ secrets.WG_PEER_PUBLIC_KEY }} \
            allowed-ips 0.0.0.0/0,::/0 \
            endpoint 138.199.21.216:51820

      - name: Bring interface up
        run: sudo ip link set up dev wg0

      - name: Test connectivity
        run: curl -v http://10.2.0.1

      - name: Run the download
        working-directory: ./TVerRec
        run: |
         pwsh src/download_bulk.ps1

      - name: Set artifact date
        id: set_artifact_date
        run: echo "ARTIFACT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Compress downloads
        run: |
          zip -r tver-downloads-${{ env.ARTIFACT_DATE }}.zip TVerRec/downloads

      - name: Create GitHub Release and Upload Asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: tver-${{ env.ARTIFACT_DATE }}
          name: TVer Downloads ${{ env.ARTIFACT_DATE }}
          files: tver-downloads-${{ env.ARTIFACT_DATE }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
